# fly.toml app configuration file generated for images-stevenberg-net on 2024-10-06T11:26:15-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'images-stevenberg-net'
primary_region = 'ewr'

[build]
image = 'shumc/imagor:latest'

[http_service]
internal_port = 8080
force_https = true
processes = ['app']

[[vm]]
memory = '1gb'
cpu_kind = 'shared'
cpus = 1
